# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:           Akshay Rangasai's Personal Web Page 
tagline:          ''
description:      ''
url:              http://akshayrangasai.com
paginate:         1

author:
  name:           'Akshay Rangasai'
  url:            https://twitter.com/ThatWasFunny da

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
