# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "akshayrangasai"



author:
  name:             Akshay Rangasai
  facebook:         akshayrangasai
  twitter:          ThatWasFunnyDa
  github:           akshayrangasai
  linkedin:         your-id
  medium:           your-id
  tumblr:           your-id
  email:            akshayrangasai.d@gmail.com

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "your-id"

# URL
url:                "http://akshayrangasai.com"
#url:               "localhost:4000"
baseurl:            ""


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Kolkata
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/About"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
  - name:           "Github"
    url:            "https://github.com/akshayrangasai"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"


# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
# - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]
