# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:           akshayrangasai 
tagline:          ''
description:      ''
url:              www.akshayrangasai.com
paginate:        5 
paginate_path:   "blog/page:num/"
baseurl:         ""

author:
  name:           'Akshay Rangasai'
  url:            https://twitter.com/ThatWasFunny da

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
